### PR TITLE
add sleep commands.

### PR DESCRIPTION
**Pull request by bebehei**
github only allows you to make 20 authenticated requests. Again, proper sunday afternoon code :wink:

### CODE REVIEW

**Comment by ttencate** [comment]
Great, thanks!

**Comment by codeguru42** [comment]
Does this issue fix #30?

**Comment by bebehei** [comment]
as @MastaP pointed out sleep(3) solves this. And this had been merged into the code ;-)

Here is the full documentation: https://developer.github.com/v3/#rate-limiting

**Comment by bebehei** [comment]
I also experienced the 403 issues. Porting the issues with sleep(3) solved my problem, too. But that happened in April, I'm not able to give you a precise statement about this.

**Pull request merged**
